#pragma once

#define PIN_DETECT (1 << 1)
#define PIN_RELS (1 << 2)
#define PIN_RELR (1 << 3)
#define PIN_LEDA (1 << 4)
#define PIN_LEDB (1 << 5)
#define PIN_BTNA (1 << 6)
#define PIN_BTNB (1 << 7)
#define PINCTRL_BTNA PIN6CTRL
#define PINCTRL_BTNB PIN7CTRL

#define CURRENT_OFF_TOLERANCE 0x10

#define REGISTER_ADC 0
#define REGISTER_ISLIGHTON 1
#define REGISTER_COUNT 2

#define EEPROM_ADDRESS_RS485_SLAVEID 0

//#define DIAGNOSTICS_LISTEN_ONLY_MODE
//#define DIAGNOSTICS_STATISTICS
#define DIAGNOSTICS_SET_ADDRESS

#define PIN_LIGHT_IS_ON PIN_LEDA
#define PIN_LED_SETUP_MODE PIN_LEDB

//#define PIN_LED_RELAY PIN_LEDB